image: node:latest

before_script:
  - npm install

cache:
  paths:
  - node_modules

stages:
  - test
  - build

test_job:
  stage: test
  script:
    - npm test
  cache:
    policy: pull

build_job:
  stage: build
  script:
    - npm run build
  cache:
    policy: pull
