defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: rdfriedl/circleci-node-aws

version: 2
jobs:
  build:
    <<: *defaults

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Install dependancies
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: gulp build
          command: npm run build

      - persist_to_workspace:
          root: ./
          paths:
            - dist
  deploy:
    <<: *defaults

    steps:
      - attach_workspace:
          at: /tmp/workspace

      - deploy:
          name: Deploy to s3 bucket
          command: |
            aws configure set preview.cloudfront true && \
            echo delopying to bucket ${S3_BUCKET} && \
            aws s3 rm s3://${S3_BUCKET} --recursive && \
            aws s3 sync /tmp/workspace/dist s3://${S3_BUCKET} --acl public-read && \
            aws cloudfront create-invalidation --distribution-id ${CLOUDFRONT_ID} --paths "/*";


workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master